-- this query will pull the KPI reports for USRider tab of the Marketing Performance & Traffic sheet (MPTs) for April 2023 to Sep 2023
-- the variance btwn the numbers generated by this query and those recorded in the MPTs 
-- are greater than those returned by the Spalding Labs version of this query (July 2023 Impressions and ROAS are particularly different)
-- interestingly CTR is almost exactly the same
-- subsequent months will need to be added manually as applicable

-- NOTES --
-- why is Sep 2023 clicks SO HIGH? - why is it not reflected in YTD clicks? 


(SELECT 
	DV360_Campaign, 
	'YTD' AS Month, 
	sum(cast(DV360_Cost_USD as decimal(18,4))) AS 'DV360 cost',
	sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4))) AS 'total revenue',
	sum(cast(Total_Conversions AS decimal(18,4))) AS 'total conversions',
	sum(CAST(Active_View_Viewable_Impressions AS int)) As 'impressions',
	sum(CAST(Clicks AS int)) AS 'clicks',
	ROUND((sum(CAST(Clicks AS decimal))/sum(CAST(Active_View_Viewable_Impressions AS decimal)))*100, 2) AS 'CTR',
	ROUND((sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4)))/sum(cast(DV360_Cost_USD as decimal(18,4))))*100, 2) AS 'ROAS',
	ROUND(sum(cast(DV360_Cost_USD as decimal(18,4)))/sum(cast(Total_Conversions AS decimal(18,4))),2) AS 'CPA'
FROM email_reports.all_advertisers_campaign_manager_view aacmv 
WHERE DV360_Campaign = 'USRider' AND [Date] BETWEEN '2023-01-01' AND '2023-08-31'
GROUP BY DV360_Campaign)
UNION 
(SELECT 
	DV360_Campaign, 
	'September 2023' AS Month, 
	sum(cast(DV360_Cost_USD as decimal(18,4))) AS 'DV360 cost',
	sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,2))) AS 'total revenue',
	sum(cast(Total_Conversions AS decimal(18,4))) AS 'total conversions',
	sum(CAST(Active_View_Viewable_Impressions AS int)) As 'impressions',
	sum(CAST(Clicks AS int)) AS 'clicks',
	ROUND((sum(CAST(Clicks AS decimal))/sum(CAST(Active_View_Viewable_Impressions AS decimal)))*100, 2) AS 'CTR',
	ROUND((sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4)))/sum(cast(DV360_Cost_USD as decimal(18,4))))*100, 2) AS 'ROAS',
	ROUND(sum(cast(DV360_Cost_USD as decimal(18,4)))/sum(cast(Total_Conversions AS decimal(18,4))),2) AS 'CPA'
FROM 
	email_reports.all_advertisers_campaign_manager_view aacmv 
WHERE 
	DV360_Campaign = 'USRider' AND [Date] BETWEEN '2023-09-01' AND '2023-09-30'
GROUP BY 
	DV360_Campaign)
UNION 
(SELECT 
	DV360_Campaign, 
	'August 2023' AS Month, 
	sum(cast(DV360_Cost_USD as decimal(18,4))) AS 'DV360 cost',
	sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,2))) AS 'total revenue',
	sum(cast(Total_Conversions AS decimal(18,4))) AS 'total conversions',
	sum(CAST(Active_View_Viewable_Impressions AS int)) As 'impressions',
	sum(CAST(Clicks AS int)) AS 'clicks',
	ROUND((sum(CAST(Clicks AS decimal))/sum(CAST(Active_View_Viewable_Impressions AS decimal)))*100, 2) AS 'CTR',
	ROUND((sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4)))/sum(cast(DV360_Cost_USD as decimal(18,4))))*100, 2) AS 'ROAS',
	ROUND(sum(cast(DV360_Cost_USD as decimal(18,4)))/sum(cast(Total_Conversions AS decimal(18,4))),2) AS 'CPA'
FROM email_reports.all_advertisers_campaign_manager_view aacmv 
WHERE DV360_Campaign = 'USRider' AND [Date] BETWEEN '2023-08-01' AND '2023-08-31'
GROUP BY DV360_Campaign)
UNION 
(SELECT 
	DV360_Campaign, 
	'July 2023' AS Month,
	sum(cast(DV360_Cost_USD as decimal(18,4))) AS 'DV360 cost',
	sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4))) AS 'total revenue',
	sum(cast(Total_Conversions AS decimal(18,4))) AS 'total conversions',
	sum(CAST(Active_View_Viewable_Impressions AS int)) As 'impressions',
	sum(CAST(Clicks AS int)) AS 'clicks',
	ROUND((sum(CAST(Clicks AS decimal))/sum(CAST(Active_View_Viewable_Impressions AS decimal)))*100, 2) AS 'CTR',
	ROUND((sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4)))/sum(cast(DV360_Cost_USD as decimal(18,4))))*100, 2) AS 'ROAS',
	ROUND(sum(cast(DV360_Cost_USD as decimal(18,4)))/sum(cast(Total_Conversions AS decimal(18,4))),2) AS 'CPA'
FROM email_reports.all_advertisers_campaign_manager_view aacmv 
WHERE DV360_Campaign = 'USRider' AND [Date] BETWEEN '2023-07-01' AND '2023-07-31'
GROUP BY 
	DV360_Campaign)
UNION 
(SELECT 
	DV360_Campaign, 
	'June 2023' AS Month,
	sum(cast(DV360_Cost_USD as decimal(18,4))) AS 'DV360 cost',
	sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4))) AS 'total revenue',
	sum(cast(Total_Conversions AS decimal(18,4))) AS 'total conversions',
	sum(CAST(Active_View_Viewable_Impressions AS int)) As 'impressions',
	sum(CAST(Clicks AS int)) AS 'clicks',
	ROUND((sum(CAST(Clicks AS decimal))/sum(CAST(Active_View_Viewable_Impressions AS decimal)))*100, 2) AS 'CTR',
	ROUND((sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4)))/sum(cast(DV360_Cost_USD as decimal(18,4))))*100, 2) AS 'ROAS',
	ROUND(sum(cast(DV360_Cost_USD as decimal(18,4)))/sum(cast(Total_Conversions AS decimal(18,4))),2) AS 'CPA'
FROM email_reports.all_advertisers_campaign_manager_view aacmv 
WHERE DV360_Campaign = 'USRider' AND [Date] BETWEEN '2023-06-01' AND '2023-06-30'
GROUP BY 
	DV360_Campaign)
UNION 
(SELECT 
	DV360_Campaign, 
	'May 2023' AS Month,
	sum(cast(DV360_Cost_USD as decimal(18,4))) AS 'DV360 cost',
	sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4))) AS 'total revenue',
	sum(cast(Total_Conversions AS decimal(18,4))) AS 'total conversions',
	sum(CAST(Active_View_Viewable_Impressions AS int)) As 'impressions',
	sum(CAST(Clicks AS int)) AS 'clicks',
	ROUND((sum(CAST(Clicks AS decimal))/sum(CAST(Active_View_Viewable_Impressions AS decimal)))*100, 2) AS 'CTR',
	ROUND((sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4)))/sum(cast(DV360_Cost_USD as decimal(18,4))))*100, 2) AS 'ROAS',
	ROUND(sum(cast(DV360_Cost_USD as decimal(18,4)))/sum(cast(Total_Conversions AS decimal(18,4))),2) AS 'CPA'
FROM email_reports.all_advertisers_campaign_manager_view aacmv 
WHERE DV360_Campaign = 'USRider' AND [Date] BETWEEN '2023-05-01' AND '2023-05-31'
GROUP BY 
	DV360_Campaign)
UNION 
(SELECT 
	DV360_Campaign, 
	'April 2023' AS Month,
	sum(cast(DV360_Cost_USD as decimal(18,4))) AS 'DV360 cost',
	sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4))) AS 'total revenue',
	sum(cast(Total_Conversions AS decimal(18,4))) AS 'total conversions',
	sum(CAST(Active_View_Viewable_Impressions AS int)) As 'impressions',
	sum(CAST(Clicks AS int)) AS 'clicks',
	ROUND((sum(CAST(Clicks AS decimal))/sum(CAST(Active_View_Viewable_Impressions AS decimal)))*100, 2) AS 'CTR',
	ROUND((sum(cast(Spalding_Labs_Conversion_Purchase_EN_SL_Conversion_Purchase_Total_Revenue as decimal(18,4)))/sum(cast(DV360_Cost_USD as decimal(18,4))))*100, 2) AS 'ROAS',
	ROUND(sum(cast(DV360_Cost_USD as decimal(18,4)))/sum(cast(Total_Conversions AS decimal(18,2))),2) AS 'CPA'
FROM email_reports.all_advertisers_campaign_manager_view aacmv 
WHERE DV360_Campaign = 'USRider' AND [Date] BETWEEN '2023-04-01' AND '2023-04-30'
GROUP BY 
	DV360_Campaign)





	